language: python
dist: bionic
python:
  - '3.8'
services:
  - redis
before_install:
  - sudo apt-get install -y libimage-exiftool-perl dcraw wget
  - wget http://gb.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.29-0ubuntu2_amd64.deb
  - sudo dpkg -i libc6_2.29-0ubuntu2_amd64.deb
  - wget http://gb.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-bin_2.29-0ubuntu2_amd64.deb
  - sudo dpkg -i libc-bin_2.29-0ubuntu2_amd64.deb
install:
  - pip install -r requirements.txt
script:
  - coverage run test.py
after_success:
  - codecov
