language: python
python:
  - '3.6'
services:
  - redis
before_install:
  - sudo apt-get install -y libimage-exiftool-perl
install:
  - pip install pipenv && pipenv install --system --skip-lock
script:
  - coverage run backend/test.py
after_success:
  - codecov
