dist: xenial
language: python
python:
  - '3.6'
services:
  - redis
before_install:
  - sudo apt-get install -y libimage-exiftool-perl dcraw
install:
  - pip install -r requirements.txt
script:
  - coverage run backend/test.py
after_success:
  - codecov
