version: "2"

services:
  postgres:
    container_name: photonix-postgres
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photo-manager
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    container_name: photonix-redis
    image: redis:3.2.8

  photonix:
    container_name: photonix
    image: damianmoore/photonix:latest
    ports:
     - "8888:80"
    environment:
      ENV: prd
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      ALLOWED_HOSTS: localhost,example.com
    volumes:
     - ./data/photos:/data/photos
     - ./data/cache:/data/cache
     - ./data/models:/data/models
    links:
     - postgres
     - redis
