version: "2"

services:
  postgres:
    container_name: pm-postgres
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photo-manager
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    container_name: pm-redis
    image: redis:3.2.8

  photo-manager:
    container_name: photo-manager
    image: damianmoore/photo-manager:latest
    ports:
     - "8888:80"
    environment:
      ENV: prd
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    volumes:
     - ./data/photos:/data/photos
     - ./data/cache:/data/cache
     - ./data/models:/data/models
    links:
     - postgres
     - redis
